### ISSUE TITLE
Missing C++ Build Flag causing pip failure on MacOS Mojave Python 3.7

### ISSUE THREAD

**Issue by dmaljovec** [fmder/ghalton#11]
Thanks for the great project! I have been using your library with some success in the past, but noticed an issue on a fresh install that I was hoping I could help out with.

I just tried to do a pip install into a fresh python 3.7 virtual environment on a MacOS Mojave system and received the following error:

```
pip install ghalton
Collecting ghalton
  Downloading https://files.pythonhosted.org/packages/36/d3/88ccf26adde4930247dd58367ba896d149579fcbbe381e278e7c9b25db09/ghalton-0.6.1.tar.gz (125kB)
     |████████████████████████████████| 133kB 786kB/s
Building wheels for collected packages: ghalton
  Building wheel for ghalton (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: [directory obfuscated]/miniconda3/envs/samply/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sc/j5wn6cv55pj8d65qg4rgdn715k4qkm/T/pip-install-lkc_y4n8/ghalton/setup.py'"'"'; __file__='"'"'/private/var/folders/sc/j5wn6cv55pj8d65qg4rgdn715k4qkm/T/pip-install-lkc_y4n8/ghalton/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/sc/j5wn6cv55pj8d65qg4rgdn715k4qkm/T/pip-wheel-c4h3ob5i --python-tag cp37
       cwd: /private/var/folders/sc/j5wn6cv55pj8d65qg4rgdn715k4qkm/T/pip-install-lkc_y4n8/ghalton/
  Complete output (20 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.7
  creating build/lib.macosx-10.7-x86_64-3.7/ghalton
  copying ghalton/ghalton_wrapper.py -> build/lib.macosx-10.7-x86_64-3.7/ghalton
  copying ghalton/constants.py -> build/lib.macosx-10.7-x86_64-3.7/ghalton
  copying ghalton/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/ghalton
  running build_ext
  building 'ghalton._ghalton_wrapper' extension
  creating build/temp.macosx-10.7-x86_64-3.7
  creating build/temp.macosx-10.7-x86_64-3.7/src
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I[directory obfuscated]/miniconda3/envs/samply/include -arch x86_64 -I[directory obfuscated]/miniconda3/envs/samply/include -arch x86_64 -I[directory obfuscated]/miniconda3/envs/samply/include/python3.7m -c src/Halton_wrap.cxx -o build/temp.macosx-10.7-x86_64-3.7/src/Halton_wrap.o
  warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  src/Halton_wrap.cxx:3044:10: fatal error: 'stdexcept' file not found
  #include <stdexcept>
           ^~~~~~~~~~~
  1 warning and 1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for ghalton
  Running setup.py clean for ghalton
Failed to build ghalton
Installing collected packages: ghalton
    Running setup.py install for ghalton ... error
    ERROR: Command errored out with exit status 1:
     command: [directory obfuscated]/miniconda3/envs/samply/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sc/j5wn6cv55pj8d65qg4rgdn715k4qkm/T/pip-install-lkc_y4n8/ghalton/setup.py'"'"'; __file__='"'"'/private/var/folders/sc/j5wn6cv55pj8d65qg4rgdn715k4qkm/T/pip-install-lkc_y4n8/ghalton/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/sc/j5wn6cv55pj8d65qg4rgdn715k4qkm/T/pip-record-d_u0q2gl/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/sc/j5wn6cv55pj8d65qg4rgdn715k4qkm/T/pip-install-lkc_y4n8/ghalton/
    Complete output (20 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.7
    creating build/lib.macosx-10.7-x86_64-3.7/ghalton
    copying ghalton/ghalton_wrapper.py -> build/lib.macosx-10.7-x86_64-3.7/ghalton
    copying ghalton/constants.py -> build/lib.macosx-10.7-x86_64-3.7/ghalton
    copying ghalton/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/ghalton
    running build_ext
    building 'ghalton._ghalton_wrapper' extension
    creating build/temp.macosx-10.7-x86_64-3.7
    creating build/temp.macosx-10.7-x86_64-3.7/src
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I[directory obfuscated]/miniconda3/envs/samply/include -arch x86_64 -I[directory obfuscated]/miniconda3/envs/samply/include -arch x86_64 -I[directory obfuscated]/miniconda3/envs/samply/include/python3.7m -c src/Halton_wrap.cxx -o build/temp.macosx-10.7-x86_64-3.7/src/Halton_wrap.o
    warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    src/Halton_wrap.cxx:3044:10: fatal error: 'stdexcept' file not found
    #include <stdexcept>
             ^~~~~~~~~~~
    1 warning and 1 error generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: [directory obfuscated]/miniconda3/envs/samply/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sc/j5wn6cv55pj8d65qg4rgdn715k4qkm/T/pip-install-lkc_y4n8/ghalton/setup.py'"'"'; __file__='"'"'/private/var/folders/sc/j5wn6cv55pj8d65qg4rgdn715k4qkm/T/pip-install-lkc_y4n8/ghalton/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/sc/j5wn6cv55pj8d65qg4rgdn715k4qkm/T/pip-record-d_u0q2gl/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
```

I feel like I have dealt with this problem before on my own projects, and I was able to fix it by doing what the compiler told me:

```
    warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
```

I don't know if this will affect builds on other systems, so I will put together a PR for you to review, if you don't mind.

**Comment by dmaljovec** [comment]
It appears adding the flag `-stdlib=libc++` to the extensions compiler flag still fails on linking. This may take more effort to debug than I originally anticipated.

**Comment by fmder** [comment]
I backed out your modification. It regressed the ability to build on linux. GCC does not have a ``-stdlib`` argument. However, I was still able to build on my mac and the MacOS version provided on Azure DevOps allowed me to build wheels for Windows, MacOS 10.13, MacOS 10.14, Manylinux2010 for Python 2.7, 3.6, 3.7 and 3.8. The wheels are now available on PyPi if you want to try them out.

**Comment by fmder** [comment]
Now I see that your are using lib.macosx-10.7-x86_64-3.7, for Mojave you should read lib.macosx-10.14-x86_64-3.7. Maybe you should check your xcode version/configuration.

**Comment by dmaljovec** [comment]
Hmm, my command line tools say they are up to date and Iam actually here because someone else was trying to install one of my libraries  which uses ghalton as a dependency. The fact that this isn’t just my machine tells me at the very least that maybe Apple isn’t doing a good job keeping users on the latest library versions. The install failed trying to build ghalton as far as I could tell:


/private/var/folders/q3/p9jmltf133n1rtsjvf_2s2c0wfs66k/T/pip-install-zbheie6t/samply/
    Complete output (146 lines):
    no previously-included directories found matching 'doc/_build'
    warning: no previously-included files matching '.DS_Store' found anywhere in distribution
    warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    src/Halton_wrap.cxx:3044:10: fatal error: 'stdexcept' file not found
    #include <stdexcept>
             ^~~~~~~~~~~
...
1146, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

If this were just my machine, I’d be happy to fix the library issue locally and be on my way, but I don’t want to ruin the user experience by telling my users to fix their std c lib on each of their machines.

How about as a compromise we wrap the extra compiler and linker flags I proposed in an `os` check? This should not affect Linux and Windows users and allow all Mac users to have a painless experience as well.

**Comment by fmder** [comment]
Yes that could be done. But I'm intrigued, I just published a wheel on pypi shouldn't your pip install use it?

**Comment by dmaljovec** [comment]
Sorry, yes, I can just pin to that version, you are correct.
